
version: 2

models:
    - name: raw_gz_sales
      description: "Satışlar Tablosu"
      columns:
          - name: orders_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: raw_gz_product
      description: "Ürünler Tablosu"
      columns:
          - name: products_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: raw_gz_ship
      description: "Kargo Tablosu"
      columns:
          - name: orders_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null